### PR TITLE
Drop support for django 1.x and python 2.x

### PR DESCRIPTION
**Pull request by imomaliev**
- Drop support for python 2.x
- Drop support for django 1.x
- Fix AdminInline for django > 2.1
- Do not install tests
- delete deprecated methods `move`, `move_up`, `move_down` and `_move`

### CODE REVIEW

**Comment by imomaliev** [comment]
@bfirsh Ready for review, didn't do much of refactoring just dropped support, will create separate PR for code cleanup and refactoring, because we need to release working version ASAP

**Comment by bfirsh** [comment]
Awesome! LGTM.

Thanks so much for this!

**Comment by imomaliev** [comment]
@bfirsh will you make a release version?

**Comment by bfirsh** [comment]
@imomaliev You can do it, if you like! Credit where credit is due. :)

Should just be a case of:

```
$ git tag 3.0.0
$ git push --tags
```

Or, through the GitHub UI.

**Comment by imomaliev** [comment]
@bfirsh I meant upload to PYPI)) Added tag and pushed it. Will it be uploaded to PYPI automatically?

**Comment by bfirsh** [comment]
Ah yes - that should be handled by Travis automatically. Looks like it worked: 
https://pypi.org/project/django-ordered-model/

**Pull request merged**
