### PR TITLE
Methods to get other elements in order.

### PR DESCRIPTION
**Pull request by sparkyb**

### CODE REVIEW

**Comment by sparkyb** [comment]
Ah. I forgot that querysets had .first() and .last(). I believe I have made all the above requested changes.

**Comment by imomaliev** [comment]
@sparkyb Hi, can you rebase?

**Comment by imomaliev** [comment]
@sparkyb Hi, can you rebase?

**Comment by sparkyb** [comment]
I didn't realize this was still outstanding. I've moved on, but I've merged the upstream changes in caes you still want to merge this pull request.

**Comment by imomaliev** [comment]
closing in favour of https://github.com/bfirsh/django-ordered-model/pull/168

**Pull request closed without merging**
