### PR TITLE
Added support for multi-table polymorfic classes, tests added as well

### PR DESCRIPTION
**Pull request by BtStSoft**
Would like to include the new option to specify the full module path to a base class in this package.

### CODE REVIEW

**Comment by mcwebb** [comment]
@BtStSoft I installed your fork but it didn't seem to solve the issue for me.
I added the `order_class_path` config to the base model. Is there anything else that needs to be done to enable the functionality?

**Comment by BtStSoft** [comment]
@mcwebb That should be enough. Maybe have a look at models.py in the tests subfolder:

    class BaseQuestion(OrderedModel):
        order_class_path = ____module____ + '.BaseQuestion'
        question = models.TextField(max_length=100)
        class Meta:
            ordering = ('order',)

    class MultipleChoiceQuestion(BaseQuestion):
        good_answer = models.TextField(max_length=100)
        wrong_answer1 = models.TextField(max_length=100)
        wrong_answer2 = models.TextField(max_length=100)
        wrong_answer3 = models.TextField(max_length=100)

    class OpenQuestion(BaseQuestion):
        answer = models.TextField(max_length=100)

As you see the BaseQuestion class is NOT abstract. So a separate table is made for the base class and all subclasses. This is called multi-table inheritance. So make sure you do not specify abstract = True in the Meta class of your Base class.

**Comment by mcwebb** [comment]
Thanks very much @BtStSoft;
Sorry, I was wrong, your fork does in fact work correctly, I just hadn't flushed my database so the order integers were all over the place.

:+1: for merge

**Comment by nickpolet** [comment]
Has there been any progress in getting this merged into master? It's really useful for some specific use cases and adds a lot of flexibility to ordered models that inherit from base classes.

**Comment by nickpolet** [comment]
This fork also needs to be rebased as it doesn't work with newer versions of django. I can see old URL imports that are causing it to fail.

**Comment by nickpolet** [comment]
I have created an updated version of this pull request that works with newer versions of django. https://github.com/bfirsh/django-ordered-model/pull/113

**Comment by shuckc** [comment]
Merged in #113, so closing this PR.

**Pull request closed without merging**
