### PR TITLE
Solved a number of open issues (#50 #51 #73 #78 #80 #82)

### PR DESCRIPTION
**Pull request by mverleg**
Sorry for putting everything into one pull request and for not writing tests, I didn't have more time.
#80 and #82 are simple but important I think, since it doesn't work on some Django versions this way.
#51 is also important I think because changing things through GET leaves one vulnerable to CSRF attacks. It looks a little voodoo but I added comments to hopefully clarify why it was needed.

The rest is less important but hopefully still useful.

Would be great if anyone has time to test it (maybe even write a test?)

### CODE REVIEW

**Comment by fric** [comment]
Hi @bfirsh, it would be great if you could consider this PR. It fixes two bugs which we ran into when using the package under Django 1.9. Due to #82, the OrderedTabularInline throws an exception and cannot be used at all.
Many thanks in advance, Felix

**Comment by bfirsh** [comment]
This unfortunately needs a rebase now, and really does need some tests.

If I get some time I'll cherry pick and fix up the fix for #82... unless somebody else gets there before me. :)

**Comment by mverleg** [comment]
Not in the next days, sorry :-(

**Comment by shuckc** [comment]
I've read through these patches:
* using the Django 1.9 bundled svg icons doesn't seem especially important, also I note the bundled admin images lacks a first/last image which has been requested a few times.
* Moving to POST-requests adds a chunk of javascript, but doesn't use the originating form handler (see `django-mqtt` code examples for a better implementation of POST+originating form) so we still need to keep the clunky URL handlers.
* Caching the number of items (per thread?) in the queryset and doing an additional query to show/hide the "outer" move up/down buttons doesn't seem particularly worthwhile
* Issue 80 has been fixed by another commit
* Issue 73 was fixed in PR 75
* The OPs interpretation of order_with_repect_to was muddled (it being optional) at the start of this patch series, causing several commits to reverse others.

Therefore suggest we close this, as the good bits are incorporated.

**Pull request closed without merging**
