### PR TITLE
Added Management Commands for Renumbering

### PR DESCRIPTION
**Pull request by src-r-r**
I noticed a bug where entries would not be renumbered after deletion (or reordering, for that matter). This management command fixes that. Hope you like it!

### CODE REVIEW

**Comment by bfirsh** [comment]
Nice, thanks! This looks great. Would you mind writing a test for it?

**Comment by freckles-the-pirate** [comment]
Alright, completed.

**Comment by bfirsh** [comment]
@freckles-the-pirate Looks like the tests are failing, I'm afraid! Might also be worth creating a separate test class for the management command tests too - they aren't related to the admin.

**Comment by freckles-the-pirate** [comment]
Alright...fixed it. the failed test wasn't related to the management commands but I fixed it anyway. Also, I refactored the management test code into a new class in test.py.

**Comment by bfirsh** [comment]
Appreciate that! Unfortunately needs rebasing now, though. :(

**Comment by imomaliev** [comment]
@src-r-r Can you rebase this?

**Pull request closed without merging**
