### PR TITLE
Django 2.0 and 2.1 work

### PR DESCRIPTION
**Pull request by hdknr**
OrderedModelAdmin fix for 2.1

### CODE REVIEW

**Comment by ncvc** [comment]
🎉

**Comment by bfirsh** [comment]
Thanks!

**Comment by bfirsh** [comment]
now release as 2.1.0!

**Comment by benrudolph** [comment]
I believe this only coveres `OrderedModelAdmin` and not `OrderInlineMixin`, can take a look into it

**Comment by bfirsh** [comment]
Thanks! Would be great to get a test, too.

**Pull request merged**
