### PR TITLE
Fix django21 inline

### PR DESCRIPTION
**Pull request by imomaliev**
Fix https://github.com/bfirsh/django-ordered-model/issues/152 issue with django 2.1 and also refactor `OrderedInlineMixin` to use regular methods instead of classmehods. This is probably only correct way to have them working after latest changes in django

@bfirsh This is initial version, we probably have to release it under version 3.x because this is braking change. Do you have any comments against this approach?

### CODE REVIEW

**Comment by bfirsh** [comment]
Nope - had a quick look through and this looks good to me. Thank you!

**Comment by benrudolph** [comment]
👏  interesting

**Comment by bfirsh** [comment]
@imomaliev :+1:

I wonder if there are any other breaking changes worth rolling into this...

**Comment by imomaliev** [comment]
@bfirsh I will review existing PRs and see what could be add as well

**Comment by bfirsh** [comment]
Sweet! Give me a shout if there is anything I can help with, or review, or whatever.

**Comment by imomaliev** [comment]
@bfirsh what about dropping python 2 support?

**Comment by bfirsh** [comment]
Yeah, I’d be down. The current version seems reasonably stable for Django 1.x (and we always release another minor version). Also means we can drop support for Django 1.x, I suppose. :)

**Pull request merged**
