### PR TITLE
Fix #73: Remove usage of deprecated django.conf.urls.patterns.

### LINKED ISSUE #73: Admin URL config deprecation
Hi, thanks for a really great module.
Just thought I should report (since it doesn't seem to have been reported yet), I'm getting the following deprecation warning for this module.

```
[...]/site-packages/ordered_model/admin.py:32:
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10.
Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='{app}_{model}_order_down'.format(**self._get_model_info())),
```

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by bfirsh** [comment]
Oops - needs a rebase now. sorry about that.

**Comment by timgraham** [comment]
No problem, I saw that was going to happen.

**Comment by timgraham** [comment]
Rebased and ready for merge.

**Comment by bfirsh** [comment]
Excellent. Thank you!

**Pull request merged**
