### PR TITLE
Migrate to github-actions using tox-gh-actions workflow

### PR DESCRIPTION
**Pull request by shuckc**
This is a work in progress towards #238  - several things are missing, notably secrets for package publishing to pypi, plus secrets for uploading codecov results. I've based it on the package `tox-gh-actions` (replacing `tox-travis`) closely copying how tox-gh-actions implement builds/publishing for their own repo https://github.com/ymyzk/tox-gh-actions 

The first 'dimension' of the build matrix is duplicated between `tox` and the github action matrix, which is slightly more maintenance but provides better feedback on the PR status updates, ie. you see pass/fail stats on the PR rather than needing to dive into the logs.

### CODE REVIEW

**Comment by imomaliev** [comment]
I disabled travis. Try re-commiting
Screen Shot 2021-04-08 at 19 26 19

**Comment by shuckc** [comment]
@imomaliev there is still one Travis check shown above, not sure if we need to merge travis removal to master first?
Do you have any idea why we run coverage with `coverage run` rather than using pytest to write coverage.xml? Is the upload of results automatic with that command?

**Comment by shuckc** [comment]
@imomaliev under Github project admin we need to un-configure the 'Required status' GitHub is looking for. Seems you've disabled the builder on the travis side, but not this expectation, so we're stuck.

**Comment by imomaliev** [comment]
@bfirsh I think we need your help on this one. Could you either give us admin rights to this repo or disable travis yourself?

**Comment by shuckc** [comment]
I've spoken to Ben, and asked he remove the old branch protection rules (waiting for Travis statuses) so that we can merge and bed in the new Github action rules. As this is a personal repo we can't delegate the management of either secrets or branch protection rules to Collaborators, or become Admins (Ben is willing - however Github don't allow it) so we should probably resume discussions on #172 to move over to an Organisation.

**Comment by bfirsh** [comment]
Branch protection removed! I haven't reviewed this so I'll give you the honor of merging. :)

**Comment by shuckc** [comment]
I've pushed a package to pypi test https://test.pypi.org/project/django-ordered-model/ using `twine` and the new Pypi API keys. I will push a further to the github action to run this after a tagged merge to master. The secret won't be defined until we get the project migrated over to the new org but it will be ready when we do.

**Comment by shuckc** [comment]
@imomaliev let me know if you have an account on Pypi and I'll send you an invite.

**Comment by imomaliev** [comment]
@shuckc Great! https://pypi.org/user/imomaliev/

**Comment by imomaliev** [comment]
Also could you make me an admin in new organisation?

**Comment by shuckc** [comment]
@imomaliev added you to pypi, and upgraded on the gh org to owner. Thanks for accepting

**Comment by imomaliev** [comment]
@shuckc Thanks

**Pull request merged**
